const playersData = [
    { name: "Arya", 
      overall: 61,
      pace: 76, 
      shooting: 43, 
      passing: 72, 
      dribbling: 70, 
      defence: 70, 
      physical: 51, 
      basePrice: 45,
      positions: ["CB", "RB"],
      chemistryWith: ["Amelia", "Niyaaz"] },

    { name: "Danny", 
      overall: 86,
      pace: 85, 
      shooting: 84, 
      passing: 85, 
      dribbling: 86, 
      defence: 87, 
      physical: 82, 
      basePrice: 100, 
      positions: ["GK", "CB", "CDM"],
      chemistryWith: ["Ebrahim", "Irfaan", "Zaiyaan"] },

    { name: "Liya", 
      overall: 78,
      pace: 78, 
      shooting: 83, 
      passing: 81, 
      dribbling: 83, 
      defence: 75, 
      physical: 70, 
      basePrice: 55, 
      positions: ["LWB", "LB", "LM"],
      chemistryWith: ["Irfaan", "Arya", "Amelia"] },

    { name: "Ebrahim", 
      overall: 90,
      pace: 86, 
      shooting: 91, 
      passing: 88, 
      dribbling: 91, 
      defence: 86, 
      physical: 84, 
      basePrice: 110, 
      positions: ["CM", "CAM", "CDM"],
      chemistryWith: ["Qiyam", "Danny", "Irfaan", "Zaiyaan"] },

    { name: "Irfaan", 
      overall: 79,
      pace: 77, 
      shooting: 85, 
      passing: 88, 
      dribbling: 84, 
      defence: 70, 
      physical: 80, 
      basePrice: 80, 
      positions: ["CM", "RM"],
      chemistryWith: ["Ebrahim", "Danny", "Zaiyaan", "Qiyam"] },

    { name: "Qiyam", 
      overall: 84,
      pace: 88, 
      shooting: 86, 
      passing: 83, 
      dribbling: 89, 
      defence: 40, 
      physical: 69, 
      basePrice: 90, 
      positions: ["LW"],
      chemistryWith: ["Ryan", "Irfaan", "Ebrahim"] },

    { name: "Zaiyaan", 
      overall: 90,
      pace: 90, 
      shooting: 92, 
      passing: 86, 
      dribbling: 92, 
      defence: 80, 
      physical: 84, 
      basePrice: 110, 
      positions: ["CM", "CAM", "ST"],
      chemistryWith: ["Ebrahim", "Irfaan", "Danny"] },

    { name: "Ryan", 
      overall: 75,
      pace: 75, 
      shooting: 85, 
      passing: 80, 
      dribbling: 82, 
      defence: 67, 
      physical: 77, 
      basePrice: 70, 
      positions: ["ST"],
      chemistryWith: ["Qiyam", "Danny"] },

    { name: "Sulaiman", 
      overall: 82,
      pace: 77, 
      shooting: 50, 
      passing: 60, 
      dribbling: 50, 
      defence: 78, 
      physical: 65, 
      basePrice: 100, 
      positions: ["GK"],
      chemistryWith: ["Qiyam"] },

    { name: "Niyaaz", 
      overall: 72,
      pace: 80, 
      shooting: 68, 
      passing: 60, 
      dribbling: 65, 
      defence: 80, 
      physical: 80, 
      basePrice: 68, 
      positions: ["CB", "GK"],
      chemistryWith: ["Amelia", "Zaiyan"] },

    { name: "Amelia", 
      overall: 64,
      pace: 76, 
      shooting: 43, 
      passing: 72, 
      dribbling: 70, 
      defence: 70, 
      physical: 51, 
      basePrice: 40,
      positions: ["CB", "RB"],
      chemistryWith: ["Niyaaz", "Arya", "Liya"] },

    { name: "Dummy4", overall: 80, pace: 80, shooting: 80, passing: 80, dribbling: 80, defence: 80, physical: 80, basePrice: 1, positions: ["ST"], chemistryWith: [] },
    { name: "Dummy5", overall: 90, pace: 90, shooting: 90, passing: 90, dribbling: 90, defence: 90, physical: 90, basePrice: 1, positions: ["CAM"], chemistryWith: [] }
];
