const playersData = [
    { name: "Arya", 
      pace: 76, 
      shooting: 43, 
      passing: 72, 
      dribbling: 70, 
      defence: 70, 
      physical: 51, 
      basePrice: 50,
      positions: ["CB", "RB"] },

    { name: "Danny", 
      pace: 85, 
      shooting: 84, 
      passing: 85, 
      dribbling: 86, 
      defence: 87, 
      physical: 82, 
      basePrice: 130, 
      positions: ["GK", "CB", "CDM"] },

    { name: "Liya", 
      pace: 78, 
      shooting: 83, 
      passing: 81, 
      dribbling: 83, 
      defence: 75, 
      physical: 70, 
      basePrice: 65, 
      positions: ["LWB", "LB", "LM"] },

    { name: "Ebrahim", 
      pace: 86, 
      shooting: 91, 
      passing: 88, 
      dribbling: 91, 
      defence: 86, 
      physical: 84, 
      basePrice: 150, 
      positions: ["CM", "CAM", "CDM"] },

    { name: "Irfaan", 
      pace: 77, 
      shooting: 85, 
      passing: 88, 
      dribbling: 84, 
      defence: 70, 
      physical: 80, 
      basePrice: 90, 
      positions: ["CM", "RM"] },

    { name: "Qiyam", 
      pace: 88, 
      shooting: 86, 
      passing: 83, 
      dribbling: 89, 
      defence: 40, 
      physical: 69, 
      basePrice: 100, 
      positions: ["LW"] },

    { name: "Zaiyaan", 
      pace: 90, 
      shooting: 92, 
      passing: 86, 
      dribbling: 92, 
      defence: 80, 
      physical: 84, 
      basePrice: 150, 
      positions: ["CM", "CAM", "ST"] },

    { name: "Ryan", 
      pace: 75, 
      shooting: 85, 
      passing: 80, 
      dribbling: 82, 
      defence: 67, 
      physical: 77, 
      basePrice: 80, 
      positions: ["ST"] },

    { name: "Sulaiman", 
      pace: 77, 
      shooting: 50, 
      passing: 50, 
      dribbling: 50, 
      defence: 50, 
      physical: 50, 
      basePrice: 120, 
      positions: ["GK"] },

    { name: "Niyaaz", 
      pace: 80, 
      shooting: 68, 
      passing: 60, 
      dribbling: 65, 
      defence: 80, 
      physical: 80, 
      basePrice: 70, 
      positions: ["CB", "GK"] },

    { name: "Dummy3", pace: 70, shooting: 70, passing: 70, dribbling: 70, defence: 70, physical: 70, basePrice: 1, positions: ["LW", "RW"] },
    { name: "Dummy4", pace: 80, shooting: 80, passing: 80, dribbling: 80, defence: 80, physical: 80, basePrice: 1, positions: ["ST"] },
    { name: "Dummy5", pace: 90, shooting: 90, passing: 90, dribbling: 90, defence: 90, physical: 90, basePrice: 1, positions: ["CAM"] }
];